### ISSUE TITLE
Can't round trip QRcode encode/decode

### ISSUE THREAD

**Issue by kipcole9** [cocoa-xu/evision#112] opened 2022-10-15 01:45 UTC
QRcode detection is working well (as far as I can test) but when I generate a QRcode and attempt to detect it I am not having any luck. For example:
```elixir
iex> qrcode = Evision.QRCodeEncoder.encode Evision.QRCodeEncoder.create(), "This is a string"           
%Evision.Mat{
  channels: 1,
  dims: 2,
  type: {:u, 8},
  raw_type: 0,
  shape: {25, 25},
  ref: #Reference<0.1002129465.3225026580.34308>
}
iex> Evision.QRCodeDetector.detectAndDecode Evision.QRCodeDetector.qrCodeDetector(), qrcode             
{"",
 %Evision.Mat{
   channels: 2,
   dims: 2,
   type: {:f, 32},
   raw_type: 13,
   shape: {1, 4, 2},
   ref: #Reference<0.1002129465.3225026580.34310>
 }, {:error, "empty matrix"}}
```

1. The encoded image is very small, `{25, 25}` and I don't actually know how - even if its possible - to define parameters for the encoder to make the image larger.
2. I can see there is a module `Evision.QRCodeEncoder.Params` but I'm not having any success try to define a param structure. For example:
```elixir
iex> Evision.QRCodeEncoder.Params.get_mode Evision.QRCodeEncoder.Params.qrcodeencoder_params()
zsh: segmentation fault  iex -S mix
```
Thanks for your patience @cocoa-xu while I work out have to navigate the wonderful world of OpenCV/eVision - help and guidance much appreciated.

**Comment by cocoa-xu** [comment] 2022-10-15 02:35
Hi @kipcole9, that's the expected behaviour of OpenCV. It encodes the QRCode in the minimal possible size. After the obtaining the QRCode, it's recommended to resize it with 

```elixir
Evision.QRCodeEncoder.encode Evision.QRCodeEncoder.create(), "This is a string" 
|> Evision.resize({300, 300}, interpolation: Evision.cv_INTER_AREA())
|> Evision.Mat.quicklook()
|> then(&(Evision.QRCodeDetector.detectAndDecode Evision.QRCodeDetector.qrCodeDetector(), &1))
```

<img width="934" alt="Screenshot 2022-10-15 at 03 34 26" src="https://user-images.githubusercontent.com/89497197/195965059-464faaa6-402e-45d1-92e2-deea7548e558.png">

I'll look into the reasons that causes segfault when calling `Evision.QRCodeEncoder.Params.qrcodeencoder_params()`

**Comment by cocoa-xu** [comment] 2022-10-15 03:05
The issue that causes segfault when calling `Evision.QRCodeEncoder.Params.qrcodeencoder_params()` is now fixed in [a23bf49](https://github.com/cocoa-xu/evision/commit/a23bf4939c4a1bd4e230ff445995e4c2db868b95) :D

**Comment by kipcole9** [comment] 2022-10-15 03:50
Thank you @cocoa-xu. Do you ever sleep? :-)

**Comment by cocoa-xu** [comment] 2022-10-15 03:58
Sleep is overrated XD
No, I'll probably go to sleep after releasing v0.1.12, which should be super quick like in half an hour

**Comment by cocoa-xu** [comment] 2022-10-15 04:43
Okay, v0.1.12 has been released! And the related functions are working as expected :D

**Comment by cocoa-xu** [comment] 2022-10-15 13:51
Hi @kipcole9, I added an example for QRCode encoding and decoding. It's available here, [examples/qrcode.livemd](https://github.com/cocoa-xu/evision/blob/main/examples/qrcode.livemd). 

And of course, a quick and easy Run in Livebook button,

[![Run in Livebook](https://livebook.dev/badge/v1/gray.svg)](https://livebook.dev/run?url=https%3A%2F%2Fgithub.com%2Fcocoa-xu%2Fevision%2Fblob%2Fmain%2Fexamples%2Fqrcode.livemd)

Also, I'm closing this issue now as all mentioned issues should have been solved or fixed. :)

**Closed by cocoa-xu** 2022-10-15 13:51 UTC
